import { AvailabilityPerClass, Leg, SearchResponse } from "../types/schedule";

export const test_search_res = [
    {
        err_code: "0",
        org: "CGK",
        des: "HKG",
        flight_date: "20200717",
        extra_days: 0,
        schedule: [
            [
                [
                    "Q1-Q1367",
                    "CGK",
                    "HKG",
                    "20200717",
                    "20200718",
                    "1000",
                    "1400(+1)",
                    "03h00m",
                    "A319",
                    "1",
                    [
                        ["F", "8"],
                        ["C", "8"],
                        ["Y", "87"],
                    ],
                    "CGK-SIN-HKG",
                ],
            ],
            [
                [
                    [
                        "Q1-Q1555",
                        "CGK",
                        "SIN",
                        "20200717",
                        "20200717",
                        "1210",
                        "1500",
                        "01h50m",
                        "A319",
                        "0",
                        [
                            ["Y", "800"],
                            ["H", "95"],
                            ["K", "85"],
                            ["M", "75"],
                            ["Q", "65"],
                            ["S", "55"],
                            ["T", "45"],
                            ["V", "35"],
                            ["X", "25"],
                            ["W", "20"],
                            ["O", "10"],
                        ],
                        "CGK-SIN",
                    ],
                    [
                        "Q1-Q1557",
                        "SIN",
                        "HKG",
                        "20200717",
                        "20200717",
                        "1700",
                        "1900",
                        "02h00m",
                        "A319",
                        "0",
                        [["Y", "180"]],
                        "SIN-HKG",
                    ],
                ],
            ],
        ],
        ret_flight_date: "20200717",
        ret_schedule: [
            [
                [
                    "Q1-Q1368",
                    "HKG",
                    "CGK",
                    "20200717",
                    "20200717",
                    "1600",
                    "2300",
                    "08h00m",
                    "A319",
                    "1",
                    [
                        ["F", "8"],
                        ["C", "8"],
                        ["Y", "90"],
                    ],
                    "HKG-SIN-CGK",
                ],
            ],
            [
                [
                    [
                        "Q1-Q1558",
                        "HKG",
                        "SIN",
                        "20200717",
                        "20200717",
                        "1500",
                        "1700",
                        "02h00m",
                        "A319",
                        "0",
                        [
                            ["F", "8"],
                            ["C", "8"],
                            ["Y", "90"],
                        ],
                        "HKG-SIN",
                    ],
                    [
                        "Q1-Q1554",
                        "SIN",
                        "CGK",
                        "20200717",
                        "20200717",
                        "2100",
                        "2200",
                        "02h00m",
                        "A319",
                        "0",
                        [
                            ["F", "8"],
                            ["C", "8"],
                            ["Y", "90"],
                        ],
                        "SIN-CGK",
                    ],
                ],
            ],
        ],
    },
    {
        err_code: "0",
        org: "CGK",
        des: "SIN",
        flight_date: "20211220",
        extra_days: 0,
        schedule: [
            [
                [
                    "Q1-Q19998",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211221",
                    "0100",
                    "0200(+1)",
                    "00h00m",
                    "A319",
                    "0",
                    [
                        ["Y", "100"],
                        ["YY", "50"],
                        ["H", "20"],
                        ["HH", "10"],
                    ],
                    "CGK-SIN",
                    "CGK-SIN 20211220_0100-20211221_0200-00h00m",
                    "Scheduled",
                ],
                [
                    "Q1-Q1001",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211220",
                    "0800",
                    "1000",
                    "01h00m",
                    "A319",
                    "0",
                    [
                        ["Y", "100"],
                        ["C", "0"],
                        ["F", "0"],
                    ],
                    "CGK-SIN",
                    "CGK-SIN 20211220_0800-20211220_1000-01h00m",
                    "-",
                ],
                [
                    "Q1-Q1367",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211220",
                    "0800",
                    "1000",
                    "01h00m",
                    "A319",
                    "0",
                    [
                        ["Y", "90"],
                        ["C", "0"],
                        ["F", "0"],
                    ],
                    "CGK-SIN",
                    "CGK-SIN 20211220_0800-20211220_1000-01h00m",
                    "Chartered",
                ],
                [
                    "Q1-GA900",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211220",
                    "1200",
                    "1400",
                    "01h00m",
                    "A319",
                    "0",
                    [["", ""]],
                    "CGK-SIN",
                    "CGK-SIN 20211220_1200-20211220_1400-01h00m",
                    "Scheduled",
                ],
                [
                    "Q1-Q10350",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211220",
                    "1600",
                    "1900",
                    "02h00m",
                    "A319",
                    "1",
                    [
                        ["Y", "60"],
                        ["B", "30"],
                        ["A", "10"],
                        ["N", "0"],
                        ["C", "0"],
                    ],
                    "CGK-DMK-SIN",
                    "CGK-DMK 20211220_1600-20211220_1700-01h00m/DMK-SIN 20211220_1730-20211220_1900-00h30m",
                    "Scheduled",
                ],
                [
                    "Q1-Q10987",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211221",
                    "2230",
                    "0120(+1)",
                    "01h50m",
                    "A319",
                    "1",
                    [
                        ["M", "130"],
                        ["G", "100"],
                        ["L", "70"],
                        ["S", "40"],
                        ["R", "0"],
                    ],
                    "CGK-DMK-SIN",
                    "CGK-DMK 20211220_2230-20211220_2300-00h30m/DMK-SIN 20211220_2330-20211221_0120-00h50m",
                    "-",
                ],
                [
                    "Q1-Q1555",
                    "CGK",
                    "SIN",
                    "20211220",
                    "20211221",
                    "2300",
                    "0100(+1)",
                    "01h00m",
                    "A319",
                    "0",
                    [
                        ["Y", "800"],
                        ["M", "80"],
                        ["H", "70"],
                        ["K", "60"],
                        ["Q", "50"],
                        ["V", "40"],
                        ["W", "30"],
                        ["T", "20"],
                        ["S", "10"],
                        ["", ""],
                        ["O", "0"],
                        ["X", "0"],
                    ],
                    "CGK-SIN",
                    "CGK-SIN 20211220_2300-20211221_0100-01h00m",
                    "Scheduled",
                ],
            ],
            [
                [
                    [
                        "Q1-Q14567",
                        "CGK",
                        "DMK",
                        "20211220",
                        "20211220",
                        "0100",
                        "0200",
                        "01h00m",
                        "A319",
                        "0",
                        [
                            ["Y", "110"],
                            ["K", "50"],
                            ["D", "0"],
                            ["AA", "0"],
                            ["F", "0"],
                            ["J", "0"],
                        ],
                        "CGK-DMK",
                        "2",
                        "",
                    ],
                    [
                        "Q1-Q15678",
                        "DMK",
                        "SIN",
                        "20211220",
                        "20211221",
                        "0230",
                        "0330(+1)",
                        "00h00m",
                        "A321-A",
                        "0",
                        [
                            ["Y", "110"],
                            ["K", "50"],
                            ["D", "0"],
                            ["J", "0"],
                            ["F", "0"],
                            ["AA", "0"],
                        ],
                        "DMK-SIN",
                        "2",
                        "",
                    ],
                ],
                [
                    [
                        "Q1-Q14567",
                        "CGK",
                        "DMK",
                        "20211220",
                        "20211220",
                        "0100",
                        "0200",
                        "01h00m",
                        "A319",
                        "0",
                        [
                            ["Y", "110"],
                            ["K", "50"],
                            ["D", "0"],
                            ["AA", "0"],
                            ["F", "0"],
                            ["J", "0"],
                        ],
                        "CGK-DMK",
                        "2",
                        "",
                    ],
                    [
                        "Q1-Q15555",
                        "DMK",
                        "SIN",
                        "20211220",
                        "20211221",
                        "1800",
                        "1900(+1)",
                        "00h00m",
                        "A319",
                        "0",
                        [
                            ["Y", "94"],
                            ["K", "40"],
                            ["F", "0"],
                            ["J", "0"],
                        ],
                        "DMK-SIN",
                        "2",
                        "",
                    ],
                ],
                [
                    [
                        "Q1-Q10350",
                        "CGK",
                        "DMK",
                        "20211220",
                        "20211220",
                        "1600",
                        "1700",
                        "01h00m",
                        "A319",
                        "0",
                        [
                            ["Y", "60"],
                            ["B", "30"],
                            ["A", "10"],
                            ["N", "0"],
                            ["C", "0"],
                        ],
                        "CGK-DMK-SIN-HKG",
                        "2",
                        "",
                    ],
                    [
                        "Q1-Q15555",
                        "DMK",
                        "SIN",
                        "20211220",
                        "20211221",
                        "1800",
                        "1900(+1)",
                        "00h00m",
                        "A319",
                        "0",
                        [
                            ["Y", "94"],
                            ["K", "40"],
                            ["F", "0"],
                            ["J", "0"],
                        ],
                        "DMK-SIN",
                        "2",
                        "",
                    ],
                ],
            ],
        ],
        ret_flight_date: "",
        ret_schedule: [[], []],
    },
];

const getLeg_info = (schedule: any): Leg[] => {
    return schedule.map((item: any): Leg => {
        return {
            flight_number: item[0],
            org: item[1],
            des: item[2],
            departure_date: item[3],
            arrival_date: item[4],
            departure_time: item[5],
            arrival_time: item[6],
            duration: item[7],
            aircraft: item[8],
            transit: item[9],
            availability_per_class: item[10].map(
                (avItem: any): AvailabilityPerClass => {
                    return {
                        class: avItem[0],
                        availability: avItem[1],
                    };
                }
            ),
            route: item[11],
            timestamp: item[12] || null,
        };
    });
};

const getSearchResponse = (res: any) => {
    const response: SearchResponse = {
        err_code: res.err_code,
        org: res.org,
        des: res.des,
        flight_date: res.flight_date,
        extra_days: res.extra_days,
        schedule: {
            direct: getLeg_info(res.schedule[0]),
            connecting: res.schedule[1].map((item: any) => {
                return {
                    segments: getLeg_info(item),
                };
            }),
        },
        ret_flight_date: res.ret_flight_date,
        ret_schedule: {
            direct: res.ret_schedule && getLeg_info(res.ret_schedule[0]),
            connecting:
                res.ret_schedule &&
                res.ret_schedule[1].map((item: any) => {
                    return {
                        segments: getLeg_info(item),
                    };
                }),
        },
    };
    return response;
};

export { getSearchResponse };
